POST http://localhost:3333/register
Content-Type: application/json

{
  "name": "admin3",
  "email": "admin3@gmail.com",
  "password": "123",
  "bi": "123456789",
  "admin": true
}

###
POST http://localhost:3333/register
Content-Type: application/json

{
  "name": "cliente",
  "email": "cliente@gmail.com",
  "password": "123",
  "bi": "123456789"
}

###
POST http://localhost:3333/login
Content-Type: application/json

{
  "email": "admin3@gmail.com",
  "password": "123"
}

###
GET http://localhost:3333/me

###
POST http://localhost:3333/logout

###
GET http://localhost:3333/products

###
DELETE http://localhost:3333/product/1

###
GET http://localhost:3333/cartItems